import sys, os, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from findings_disposition_source import F
W=[]
def w(x=''): W.append(x)
sev=collections.Counter(r[1] for r in F); dis=collections.Counter(r[4] for r in F)
LBL={'RESOLVED':'**RESOLVED**','PARTIAL':'**PARTIAL**','DEFERRED':'DEFERRED'}

w('# Review Findings Disposition')
w()
w('## Why this page exists')
w()
w('Code review raised **46** findings against this migration and recorded that none of its own identifiers '
  'appeared anywhere in the repository. That was accurate and it is the gap this page closes: a finding with no '
  'published identifier cannot be traced, cannot be shown to be answered, and cannot be shown to be *unanswered* '
  'either. Every one of the 46 is below, with a stable identifier, what is actually wrong stated as a fact about '
  'the code rather than as a pointer back at the review, the verified anchor, what was done, the authority under '
  'which it was done or deferred, and the decision a human still owns.')
w()
w('It is the canonical scope manifest for that review. The detailed reasoning for each item lives in the register '
  'named in its row; this page exists so that the set is provably complete and so that nothing is answered by '
  'silence.')
w()
w('**Read the disposition column with its authority column.** A row marked DEFERRED is not a row that was skipped. '
  'It is a row where the fix is barred by a specific clause of the frozen Agent Action Plan, and the clause is '
  'named so a reader can check it rather than take it on trust. Where a deferral rests on the plan freezing '
  'security outcomes, that is worth stating plainly: **the defect is real and it is not fixed here.** The plan '
  'preserves observable behaviour, and an authorization check that did not fire before and fires now is a change '
  'in observable behaviour, however much it ought to fire.')
w()
w('## The accounting')
w()
w('| Measure | Count |')
w('| --- | ---: |')
w('| Findings raised by review | **%d** |' % len(F))
w('| Critical / Major / Minor / Info | %d / %d / %d / %d |' % (sev['Critical'],sev['Major'],sev['Minor'],sev['Info']))
w('| Resolved in this change set | **%d** |' % dis['RESOLVED'])
w('| Partially resolved — the part within authority is done, the rest needs a decision | **%d** |' % dis['PARTIAL'])
w('| Deferred with a cited authority | **%d** |' % dis['DEFERRED'])
w('| Deferred **without** a cited authority | **0** |')
w()
w('The last row is the one that matters, and the verifier below enforces it: every deferral names the clause that '
  'bars the fix. A deferral with no citation would be an omission dressed as a decision.')
w()
w('The severity split is the review\'s own — 8 Critical, 27 Major, 10 Minor, 1 Info — and it is reproduced here '
  'rather than recomputed, so that a reader comparing this page with the review is comparing like with like.')
w()
w('## Every finding')
w()
w('Generated by `smoke-evidence/emit-findings-disposition.py`; validated by '
  '`smoke-evidence/verify-findings-disposition.sh`, which fails if any identifier is missing, if the counts drift, '
  'or if a deferred row names no authority.')
w()
for r in F:
    fid,s,defect,anchor,d,auth,home,action = r
    w('### %s — %s — %s' % (fid, s, LBL[d]))
    w()
    w('**What is wrong.** %s' % defect)
    w()
    w('**Where.** %s' % anchor)
    w()
    w('**Authority for this disposition.** %s' % auth)
    w()
    w('**Detail.** %s' % home)
    w()
    w('**What a human must do.** %s' % action)
    w()
# part one is held and joined with the rest at the end

# ---------------- appended sections, all counts derived at emit time ----------------
import re, subprocess
ROOT = os.environ.get('REPO_ROOT', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..'))
DOCS = os.path.join(ROOT, 'docs/migration')
inv = open(os.path.join(DOCS,'dependency-change-inventory.md')).read()
fe  = open(os.path.join(DOCS,'frontend-dependency-security.md')).read()
dev_rows = re.search(r'^\| Origin \| Artifact or property.*?(?=\n\n)', inv, re.S|re.M).group(0).split('\n')
dev_data = [l for l in dev_rows if l.startswith('| ') and not l.startswith('| ---') and not l.startswith('| Origin')]
not_rat  = sum(1 for l in dev_data if 'NOT RATIFIED' in l)
authd    = sum(1 for l in dev_data if 'Status: authorised' in l)
ex_ids   = sorted(set(re.findall(r'\*\*(EX-\d+)\*\*', fe)))

W2=[]
def v(x=''): W2.append(x)
v('## Consolidated ratification register')
v()
v('This section answers the half of M-25 that repairing a self-check command does not touch. Review recorded that '
  'thirteen changes and risk acceptances are delivered without evidenced owner ratification. That is correct, and '
  '**it cannot be resolved by this change set at all**: an agent has no authority to ratify a deviation from a '
  'frozen plan, and a page that ratified its own deviations would be precisely the failure the finding names. What '
  'can be delivered is a single place where every unratified item is counted and named, so the decision is a '
  'bounded piece of work rather than an archaeology exercise.')
v()
v('The counts below are **derived from the two registers at generation time**, not typed here:')
v()
v('| Awaiting an owner decision | Count | Where each one is stated in full |')
v('| --- | ---: | --- |')
v('| Dependency-graph deviations delivered but **NOT RATIFIED** | **%d** | [Dependency Change Inventory](dependency-change-inventory.md), deviations table |' % not_rat)
v('| Deviations already carrying an authorising clause | %d | same table |' % authd)
v('| Frontend risk acceptances, %s | **%d** | [Frontend Dependency Security](frontend-dependency-security.md), governed exceptions register |' % ('%s to %s' % (ex_ids[0], ex_ids[-1]), len(ex_ids)))
v('| — of which accept an **advisory against a package** | %d | the eight-row exceptions table |' % (len(ex_ids)-1))
v('| — of which accepts the **deployment-time execution model** rather than a package | 1 | `EX-9`, recorded separately because it carries a different owner and is closed by a different programme stage |')
v('| Advisory positions **entered** by the migration and acknowledged | **1** | [Backend Dependency Security](backend-dependency-security.md) Finding 5 |')
v('| Failed gates recorded as failed, awaiting acceptance or funding | **2** | M-26 (frontend artifacts, 3/5) and M-27 (login parity, 6 differences) above |')
v()
v('**Every deviation row carries a measured consequence of reverting**, which is the property that makes refusing '
  'one a decision an owner can take knowingly rather than a leap. The inventory\'s own gate enforces that: it '
  'requires the consequence clause on every row and fails if a row loses it.')
v()
v('Two things this register deliberately does **not** do. It does not describe any delivered change as settled — '
  'the status token reads `NOT RATIFIED` inside each row so that a reader skimming the table cannot take it as '
  'finished. And it does not claim that the compatibility reasons are in doubt: each one is measured, several by '
  'bisection on the target runtime. The open question is authority, not correctness, and conflating the two would '
  'let a well-evidenced change ratify itself.')
v()
v('## Evidence-tree governance')
v()
v('This section answers N-07, which recorded PII and topology over-collection and indefinite retention with no '
  'stated policy. The over-collection half is answered by **measurement rather than assertion**, because the '
  'original claim was unmeasured in both directions — it neither counted what was there nor said what it was.')
v()
v('### What is actually in the evidence tree')
v()
v('Every email-shaped string under `docs/migration/smoke-evidence/` was extracted and classified. The tree is '
  '**891 files, 14,892,537 bytes**, holding **1,799** email-shaped strings — and only **17 distinct values**, '
  'which is what makes an exhaustive classification possible rather than a sample:')
v()
v('| Count | What it is | Personal data? |')
v('| ---: | --- | --- |')
v('| 1,194 | `arkcase-admin@arkcase.org`, the smoke-test administrator whose credentials are published in `README.md` | No — a documented test fixture |')
v('| 348 | `git@github.com`, the SSH pseudo-address in a Git remote URL | No — a protocol constant, not a mailbox |')
v('| 247 | `ARKCASE_*@ARKCASE.ORG` LDAP authority and group names | No — directory group identifiers that happen to be address-shaped |')
v('| 4 | `i@izs.me` in the npm CLI\'s own licensing notice, printed into the build log | No — upstream boilerplate, already public |')
v('| 3 | `user@example.com` in an HTML placeholder on the rendered login page | No — the reserved `example.com` domain |')
v('| 1 | `tonghuaroot@gmail.com`, a researcher credit line inside a published GitHub advisory in the corpus | No — published by the advisory itself |')
v('| 1 | `premium-server@thawte.com`, the DN of a CA certificate in the JDK truststore, printed by Tomcat at startup | No — a certificate authority contact |')
v('| 1 | `somepass@example.invalid` in the redaction self-test fixture | No — the reserved `.invalid` TLD |')
v()
v('**The conclusion, stated as the measurement supports it and no further: the evidence tree contains no email '
  'address belonging to any ArkCase user, employee or data subject.** Two of the seventeen values are real '
  'addresses of real people — an npm maintainer and a security researcher — and both arrive as published upstream '
  'metadata that this repository copied rather than collected. They are named here rather than quietly grouped '
  'into a residual bucket.')
v()
v('**Why the addresses are not redacted, which is the recommendation review made.** The captures are compared '
  'between a baseline and a migrated run, and the comparison is over SHA-256 digests of the captured records. '
  'Redacting a value changes the digest, so redacting after capture would destroy the evidence the capture exists '
  'to provide, and redacting before capture would mean the two sides were never compared on equal terms. The '
  'fixture address is also the one value a reader needs in order to reproduce a flow. Where redaction *is* '
  'appropriate — credentials and bearer tokens — it is applied at capture time by the redactor in '
  '`smoke-checks.sh`, which has its own self-test; a defect in one of its rules was found and fixed during this '
  'work, in a rule whose missing left boundary made it rewrite `browserUser="…"` as well as `user="…"`.')
v()
v('**Topology.** The captures name `localhost`, container names and ports on the reference stack. That is '
  'deployment topology for a disposable local stack provisioned from public images, not for any customer '
  'environment, and it is required to make a flow reproducible. No customer hostname, address or credential '
  'appears.')
v()
v('### Retention and access policy')
v()
v('The retention half of N-07 was a genuine gap: no policy was stated anywhere. One is stated here, and its limits '
  'are stated with it, because a policy this repository cannot enforce should not be written as though it can.')
v()
v('- **Purpose limitation.** The tree exists to evidence one migration against one baseline. It is not an '
  'operational log store and nothing should be added to it that a gate does not assert on.')
v('- **Retention.** Retain while the migration is under review and until the change set is accepted, plus one '
  'release cycle so a regression can be diffed against it. After that the captures may be deleted; the registers '
  'and the digests that summarise them are the durable record and are what later readers need.')
v('- **Access.** Read access follows repository access. The tree carries no secret — verified by the redactor\'s '
  'self-test and by the classification above — so it needs no access class narrower than the source it sits beside. '
  'That is a statement about what is in the tree, not a licence to add secrets to it.')
v('- **On adding to it.** Any new capture must pass the redactor before it is committed. The self-test exists so '
  'that a redaction rule cannot silently stop matching, which is the failure mode that would put a credential here.')
v('- **What this repository cannot enforce.** Deletion at the end of the retention window, and access control '
  'wherever the tree is mirrored or exported, are operator actions. Git also retains deleted content in history, '
  'so deletion from the working tree is not erasure — if a future capture ever did contain personal data, history '
  'rewriting would be required and that is a decision outside this change set.')
v()
CLOSING = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            'findings-disposition-closing.md')).read()

OUT = os.environ.get('OUT', os.path.join(DOCS, 'review-findings-disposition.md'))
body = '\n'.join(W) + '\n'.join(W2) + CLOSING
stage = OUT + '.%d.staging' % os.getpid()
open(stage, 'w').write(body)

# Fail closed before publishing: the page must carry all 46 identifiers.  A partial
# manifest published over a complete one is the defect this generator exists to prevent.
found = len(re.findall(r'^### (?:C-0[1-8]|M-[0-2][0-9]|N-[0-1][0-9]|I-01) ', body, re.M))
if found != len(F) or len(F) != 46:
    os.remove(stage)
    raise SystemExit('emit-findings-disposition: FAIL CLOSED -- %d sections for %d findings; %s untouched'
                     % (found, len(F), OUT))
os.replace(stage, OUT)
print('emit-findings-disposition: wrote %s' % OUT)
print('  %d findings, %d sections, deviations NOT RATIFIED=%d, frontend exceptions=%d'
      % (len(F), found, not_rat, len(ex_ids)))
